language: erlang
otp_release:
  - 18.2.1
before_script:
  - rebar get-deps
script: rebar compile ct suites=cloudi_service || ( cat logs/raw.log logs/ct_run*/cloudi.log && exit 1 )
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
