language: erlang
otp_release:
  - 25.2.1
  - 24.3.1
  - 23.3.1
  - 22.3.4.25
before_script:
  - kerl list installations
  - rebar get-deps
script: rebar compile ct suites=cloudi_service,cloudi_logger || ( cat logs/raw.log logs/ct_run*/cloudi.log && exit 1 )
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "irc.oftc.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
