language: erlang
otp_release:
  - 17.0
  - R16B03-1
  - R16B
before_script:
  - rebar get-deps
script: rebar compile ct suites=cloudi_service || ( cat logs/raw.log && exit 1 )
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
